# 2. SALES & REVENUE ANALYSIS

#2.1 Total quantity of products sold
SELECT SUM(Quantity) AS Total_Units_Sold
FROM order_details;

#2.2 Total gross sales before discount
SELECT 
    SUM(Quantity * Unit_Price) AS Gross_Sales
FROM order_details;

# 2.3 Total discount amount
SELECT 
    SUM(Quantity * Unit_Price * Discount_Percent / 100) AS Total_Discount
FROM order_details;

#2.4 Total revenue after discount
SELECT 
    SUM(
        Quantity * Unit_Price 
        * (1 - Discount_Percent / 100)
    ) AS Total_Revenue
FROM order_details;

#2.5 Average Order Value
SELECT 
    SUM(
        od.Quantity * od.Unit_Price 
        * (1 - od.Discount_Percent / 100)
    ) / COUNT(DISTINCT o.Order_ID) AS Average_Order_Value
FROM orders o
JOIN order_details od
    ON o.Order_ID = od.Order_ID;

# 2.6 Revenue by platform
SELECT 
    o.Platform,
    ROUND(
        SUM(
            od.Quantity * od.Unit_Price 
            * (1 - od.Discount_Percent / 100)
        ), 2
    ) AS Total_Revenue
FROM orders o
JOIN order_details od
    ON o.Order_ID = od.Order_ID
GROUP BY o.Platform
ORDER BY Total_Revenue DESC;

#3.1 Number of orders placed by each customer
SELECT 
    c.Customer_ID,
    c.Customer_Name,
    COUNT(o.Order_ID) AS Total_Orders
FROM customers c
JOIN orders o
    ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Total_Orders DESC;

#Orders per customer
SELECT 
    c.Customer_ID,
    c.Customer_Name,
    COUNT(o.Order_ID) AS Total_Orders,
    CASE 
        WHEN COUNT(o.Order_ID) > 1 THEN 'Repeat Customer'
        ELSE 'One-Time Customer'
    END AS Customer_Type
FROM customers c
JOIN orders o
    ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Total_Orders DESC;


# Repeat customer count
SELECT 
    COUNT(*) AS Repeat_Customers
FROM (
    SELECT Customer_ID
    FROM orders
    GROUP BY Customer_ID
    HAVING COUNT(Order_ID) > 1
) AS CustomerOrders;

#4.1 Revenue generated by each customer + customer type
SELECT 
    c.Customer_ID,
    c.Customer_Name,
    COUNT(DISTINCT o.Order_ID) AS Total_Orders,
    ROUND(SUM(
        od.Quantity * od.Unit_Price *
        (1 - od.Discount_Percent / 100)
    ), 2) AS Total_Revenue,
    CASE
        WHEN COUNT(DISTINCT o.Order_ID) > 1 THEN 'Repeat Customer'
        ELSE 'One-Time Customer'
    END AS Customer_Type
FROM customers c
JOIN orders o 
    ON c.Customer_ID = o.Customer_ID
JOIN order_details od 
    ON o.Order_ID = od.Order_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Total_Revenue DESC;


#4.2 Revenue from repeat vs one-time customers
SELECT 
    CASE
        WHEN Order_Count > 1 THEN 'Repeat Customer'
        ELSE 'One-Time Customer'
    END AS Customer_Type,
    COUNT(*) AS Number_of_Customers,
    ROUND(SUM(Total_Revenue), 2) AS Total_Revenue
FROM (
    SELECT 
        o.Customer_ID,
        COUNT(DISTINCT o.Order_ID) AS Order_Count,
        SUM(
            od.Quantity * od.Unit_Price *
            (1 - od.Discount_Percent / 100)
        ) AS Total_Revenue
    FROM orders o
    JOIN order_details od
        ON o.Order_ID = od.Order_ID
    GROUP BY o.Customer_ID
) AS CustomerSummary
GROUP BY Customer_Type;

# 5. PRODUCT & CATEGORY ANALYSIS

SELECT 
    p.Product_ID,
    p.Product_Name,
    c.Category_Name,
    p.Brand,
    SUM(od.Quantity) AS Units_Sold,
    ROUND(SUM(
        od.Quantity * od.Unit_Price *
        (1 - od.Discount_Percent / 100)
    ), 2) AS Revenue
FROM products p
JOIN categories c 
    ON p.Category_ID = c.Category_ID
JOIN order_details od 
    ON p.Product_ID = od.Product_ID
GROUP BY p.Product_ID, p.Product_Name, c.Category_Name, p.Brand
ORDER BY Revenue DESC;


#5.1 Category performance
SELECT 
    c.Category_Name,
    SUM(od.Quantity) AS Units_Sold,
    ROUND(SUM(
        od.Quantity * od.Unit_Price *
        (1 - od.Discount_Percent / 100)
    ), 2) AS Revenue
FROM categories c
JOIN products p 
    ON c.Category_ID = p.Category_ID
JOIN order_details od 
    ON p.Product_ID = od.Product_ID
GROUP BY c.Category_Name
ORDER BY Revenue DESC
LIMIT 10;


#6. TIME-BASED SALES ANALYSIS
SELECT YEAR(o.Order_Date) AS Year, MONTH(o.Order_Date) AS Month,
       COUNT(DISTINCT o.Order_ID) AS Total_Orders,
       ROUND(SUM(od.Quantity * od.Unit_Price * (1 - od.Discount_Percent / 100)), 2) AS Revenue
FROM orders o
JOIN order_details od ON o.Order_ID = od.Order_ID
GROUP BY YEAR(o.Order_Date), MONTH(o.Order_Date)
ORDER BY Year, Month;


#Yearly performance
SELECT YEAR(o.Order_Date) AS Year,
       COUNT(DISTINCT o.Order_ID) AS Total_Orders,
       ROUND(SUM(od.Quantity * od.Unit_Price * (1 - od.Discount_Percent / 100)), 2) AS Revenue
FROM orders o
JOIN order_details od ON o.Order_ID = od.Order_ID
GROUP BY YEAR(o.Order_Date)
ORDER BY Year;

#7. ORDER & PAYMENT ANALYSIS

# Order status performance
SELECT o.Order_Status, COUNT(*) AS Total_Orders,
       ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM orders), 2) AS Order_Percentage
FROM orders o
GROUP BY o.Order_Status
ORDER BY Total_Orders DESC;

# Payment method performance
SELECT p.Payment_Method, COUNT(*) AS Total_Payments,
       ROUND(SUM(p.Amount), 2) AS Total_Amount
FROM payments p
GROUP BY p.Payment_Method
ORDER BY Total_Amount DESC;

 #8. KEY BUSINESS INSIGHTS
 
#Top 10 customers by revenue
SELECT c.Customer_ID, c.Customer_Name,
       ROUND(SUM(od.Quantity * od.Unit_Price * (1 - od.Discount_Percent / 100)), 2) AS Revenue
FROM customers c
JOIN orders o ON c.Customer_ID = o.Customer_ID
JOIN order_details od ON o.Order_ID = od.Order_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Revenue DESC
LIMIT 10;

#Top 5 brands by revenue
SELECT p.Brand,
       ROUND(SUM(od.Quantity * od.Unit_Price * (1 - od.Discount_Percent / 100)), 2) AS Revenue
FROM products p
JOIN order_details od ON p.Product_ID = od.Product_ID
GROUP BY p.Brand
ORDER BY Revenue DESC
LIMIT 5;

#Average number of orders per customer
SELECT ROUND(COUNT(Order_ID) / COUNT(DISTINCT Customer_ID), 2) AS Avg_Orders_Per_Customer
FROM orders;

#Most popular payment method
SELECT Payment_Method, COUNT(*) AS Usage_Count
FROM payments
GROUP BY Payment_Method
ORDER BY Usage_Count DESC
LIMIT 1;


#Orders placed on each day of the week
SELECT DAYNAME(Order_Date) AS Day_Name, COUNT(*) AS Total_Orders
FROM orders
GROUP BY DAYNAME(Order_Date)
ORDER BY Total_Orders DESC;